TUNE=base
EXT=ppc-O3f

BENCHLANG        = C
BENCH_FLAGS      = -DSPEC_CPU2000
CC               = $(CC_PPC)
CC_PPC           = /home/paul/Desktop/winter/superopt-build/installs/crosstool-0.43-install/gcc-4.1.0-glibc-2.3.6.mod.ppc/powerpc-405-linux-gnu/bin/powerpc-405-linux-gnu-gcc -static
CC_X86           = /home/paul/Desktop/winter/superopt-build/installs/crosstool-0.43-install/gcc-4.1.0-glibc-2.3.6.mod.i386/i686-unknown-linux-gnu/bin/i686-unknown-linux-gnu-gcc -m32 -static
COPTIMIZE        = -O3 -funroll-all-loops -g
CPORTABILITY     = -DLINUX_i386
CXX              = $(CXX_PPC)
CXXOPTIMIZE      = -O3 -funroll-all-loops
CXX_PPC          = /home/paul/Desktop/winter/superopt-build/installs/crosstool-0.43-install/gcc-4.1.0-glibc-2.3.6.mod.ppc/powerpc-405-linux-gnu/bin/powerpc-405-linux-gnu-g++ -static
CXX_X86          = /home/paul/Desktop/winter/superopt-build/installs/crosstool-0.43-install/gcc-4.1.0-glibc-2.3.6.mod.i386/i686-unknown-linux-gnu/bin/i686-unknown-linux-gnu-g++ -m32 -static
F77              = g77
FC               = g77 
OS               = unix
USE_VPATH        = 0
VENDOR           = 
VPATH_CINCLUDE   = 
VPATH_CXXINCLUDE = 
VPATH_F90INCLUDE = 
VPATH_FINCLUDE   = 
VPATH_INCLUDE    = 
X86_SOFT_FLOAT_LIB = -L/cronus/sc1/sbansal/gcc/objdir/gcc -lmygcc
abstol           = 
action           = validate
backup_config    = 1
baseexe          = crafty
basepeak         = 0
benchdir         = benchspec
benchmark        = 186.crafty
bindir           = exe
changedmd5       = 0
check_md5        = 1
command_add_redirect = 0
commanderrfile   = speccmds.err
commandexe       = crafty_base.ppc-O3f
commandfile      = speccmds.cmd
commandoutfile   = speccmds.out
company_name     = XYZ Inc.
compareerrfile   = compare.err
comparefile      = compare.cmd
compareoutfile   = compare.out
compile_error    = 0
compwhite        = 
configdir        = config
configpath       = /home/paul/Desktop/winter/superopt-build/installs/spec_cpu_2000/config/spec.mycfg
datadir          = data
deletebinaries   = 0
deletework       = 0
difflines        = 10
dirprot          = 511
endian           = 1234
env_vars         = 0
exemd5           = 271ea0b5983977692a766dee65467fb4
exitvals         = spec_exit
expand_notes     = 0
ext              = ppc-O3f
fast_rundir_verify = 0
feedback         = 1
fileprot         = 511
help             = 0
hw_avail         = May-2003
hw_cpu           = AMD Opteron (TM) 150
hw_cpu_mhz       = 2400
hw_disk          = IDE, WD2000
hw_fpu           = Integrated
hw_memory        = 2 x 512 PC3200 DDR SDRAM CL2.0
hw_model         = ASUS SK8V, Opteron (TM) 150 
hw_ncpu          = 1
hw_ncpuorder     = 1
hw_ocache        = N/A
hw_other         = None
hw_parallel      = No
hw_pcache        = 64KBI + 64KBD on chip
hw_scache        = 1024KB(I+D) on chip
hw_tcache        = N/A
hw_vendor        = 
ignore_errors    = 1
ignore_sigint    = 0
inputdir         = input
iterations       = 0
license_num      = 9999
line_width       = 0
locking          = 1
log              = log
log_line_width   = 0
lognum           = 008
mach             = default
make             = specmake
make_no_clobber  = 0
makeflags        = 
max_active_compares = 0
max_users        = 1
mean_anyway      = 0
min_report_runs  = 3
minimize_builddirs = 0
minimize_rundirs = 0
name             = crafty
nc               = 0
notes0030        =   Portability:
notes0050        =    186.crafty:  CPORTABILITY=-DLINUX_i386
notes0080        =   Baseline C:   gcc -O3 -funroll-all-loops
notes0085        =   Baseline C++: g++ -O3 -funroll-all-loops
notes0086        =   Peak tuning: basepeak=yes for all peak runs.
num              = 186
obiwan           = 
optmd5           = 2b4ea97fdf870fc69d705c4eda5a7200
os_exe_ext       = 
output           = asc
output_format    = asc,html,config
outputdir        = output
path             = /home/paul/Desktop/winter/superopt-build/installs/spec_cpu_2000/benchspec/CINT2000/186.crafty
prefix           = 
rate             = 0
rawfile          = 
rawformat        = 0
rebuild          = 1
ref_tree_level   = Top level Config
reftime          = reftime
reltol           = 
reportable       = 0
resultdir        = result
run              = all
safe_eval        = 1
setprocgroup     = 1
sigint           = 2
size             = ref
skiptol          = 
smarttune        = base
specdiff         = specdiff
specmake         = Makefile.spec
specrun          = specinvoke
srcalt           = 
srcdir           = src
subworkdir       = work
sw_avail         = Dec-2003
sw_compiler0000  = gcc and g77 3.3.x compiler
sw_file          = Linux/ext3
sw_os            = SuSE Linux 9.2 for x86
sw_state         = Multi-user SuSE Run level 3
table            = 1
teeout           = yes
teerunout        = yes
test_date        = 
tester_name      = XYZ Inc.
top              = /home/paul/Desktop/winter/superopt-build/installs/spec_cpu_2000
tune             = base
uid              = 1000
unbuffer         = 0
use_submit_for_speed = 0
username         = paul
users            = 1
vendor           = anon
vendor_makefiles = 0
verbose          = 5
version          = 0
workdir          = run
worklist         = list
